language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database palette_picker_test;' -U postgres
notifications:
- email: false
deploy:
  provider: heroku
  api_key:
    secure: aR/kO126vzE3eF/lBf7OcahNcJaIM6CFPF4KW5qEhztxqK4FWGrbnG6z0AhfSTAKO7hkRuVjQ1UycFIGSlWp6gbCUNcV851oMqi7/G/aoVrGELvyNCYQs+AKjwGkMWq+u/AYw8JSipVjLRVNnvdrFwUwcH+hZ0ZWGfrTMIgcboRhoAqGq7Sac6jRz6P3rAw6bHqUuSOEFkRSAfF2eKPsKWBXaiaQEkdAvZw9AZfz/tEdOJ1OigZrFtT3HTdkSoNHTlpy6A73tzfFQFmNFWtMw0OApiECEmHtrIslQuvrKx5DPUw6P7UqzuP4ED8/4sB6GxYOKZL7ruQtSdj+9z4Y3HWU1ZAdjFrSflayOFFx5IHU4b3F9C0JDWPT1rlUKtlz1Eh8SntH611XT+8jRpixuiBjI5jQbUbFKsT4Eh88UAUjz7CPgYSx7Eh2ry9yT/StLM0g9v2KLIuLjr+xuC6PUvYNsovO+H7pKpUFZ1VNlYtRQSwR1KULrtfFFEbD7tJEHE1wH1SJVPKFeBnIHpDp2HVEGuf/0WTia0fYJoHFHjtD5cJ5dIcszm2hHgV0ZyhFCsGCj51jWLpQnoowKFZr5qa60UfbpMvs2lQlIlGcOoFL6x0avqBkGqSqmnS8F5T31wcn1ypVc/6gC9YmH9vevCm4381r12zRDt1DB8MxmuI=
  app: palette-picker
  skip_cleanup: true
